gfxfundamentals/threejsfundamentals

- threejs/lessons/threejs-shadows.md
Sentence seems odd without the 'to'
> Minor grammar fix to shadows article

- threejs/lessons/fr/langinfo.hanson
- threejs/lessons/fr/threejs-fundamentals.md
- threejs/lessons/fr/threejs-prerequisites.md
- threejs/lessons/fr/threejs-responsive.md
@jydidier I fixed grammar errors and change some sentence. My english and french is poor so please review it. I also replace matériau by matière I guess it's a better translation.
> Fix french sentences for #51

- threejs/lessons/fr/threejs-fundamentals.md
Fix additional typos some added by myself in the previous commit :(
> Fix french sentences #52

- package-lock.json
- threejs/lessons/kr/index.md
- threejs/lessons/kr/langinfo.hanson
- threejs/lessons/kr/threejs-cameras.md
- threejs/lessons/kr/threejs-custom-buffergeometry.md
- threejs/lessons/kr/threejs-custom-geometry.md
- threejs/lessons/kr/threejs-fog.md
- threejs/lessons/kr/threejs-fundamentals.md
- threejs/lessons/kr/threejs-lights.md
- threejs/lessons/kr/threejs-materials.md
- threejs/lessons/kr/threejs-prerequisites.md
- threejs/lessons/kr/threejs-primitives.md
- threejs/lessons/kr/threejs-rendertargets.md
- threejs/lessons/kr/threejs-responsive.md
- threejs/lessons/kr/threejs-scenegraph.md
- threejs/lessons/kr/threejs-setup.md
- threejs/lessons/kr/threejs-shadows.md
- threejs/lessons/kr/threejs-textures.md
- threejs/lessons/kr/toc.html
Hi!
This is a korean translation for your series.
There are still much to go but I covered the most basic part of your series, so I think it's fine to go public.
If there are any problems, plz let me know.
And hundreds thanks to your AWESOME work 😆b!
> Korean translation

- threejs/lessons/fr/threejs-primitives.md
@Mars073 I fixed typos, grammar and redo some sentences: less pure translation and use (I hope) more french idioms. Please give me feedback on this PR.
> Fix French sentences concerning the Primitives lesson #77

- threejs/lessons/threejs-multiple-scenes.md
- threejs/threejs-multiple-scenes-copy-canvas.html
I should have sent pull request at once..
but I didn't expect there are more.
> fix examples on "threejs-multiple-scenes.md"

- threejs/lessons/kr/threejs-offscreencanvas.md
- threejs/lessons/kr/threejs-optimize-lots-of-objects-animated.md
- threejs/lessons/kr/threejs-optimize-lots-of-objects.md
Includes all articles in optimization category.
Hope this is that clean pull request you want🤗.
> korean translations

- threejs/lessons/kr/threejs-align-html-elements-to-3d.md
- threejs/lessons/kr/threejs-billboards.md
- threejs/lessons/kr/threejs-canvas-textures.md
- threejs/lessons/kr/threejs-cleanup.md
- threejs/lessons/kr/threejs-game.md
- threejs/lessons/kr/threejs-indexed-textures.md
- threejs/lessons/kr/threejs-shadertoy.md
- threejs/lessons/kr/threejs-voxel-geometry.md
korean translations for **Solutions** category.
> kr translations

- threejs/lessons/kr/threejs-backgrounds.md
- threejs/lessons/kr/threejs-offscreencanvas.md
> update kr translations r115 to r119

- threejs/lessons/kr/threejs-optimize-lots-of-objects-animated.md
- threejs/lessons/kr/threejs-tips.md
fix typo in `threejs-tips.md`
fix out-of-date issue in `threejs-optimize-lots-of-objects-animated.md`
> Fix typo & out-of-date issue

- threejs/lessons/ja/threejs-scenegraph.md
translate threejs-scenegraph.md of ja.
> translate ja of scenegraph

- threejs/lessons/zh_cn/threejs-fundamentals.md
I updated the threejsfundamentals article in zh_cn #101
> update the chinese threejsfundamentals article

- threejs/lessons/zh_cn/lang.css
- threejs/lessons/zh_cn/langinfo.hanson
Change-Id: I0820dbe78552ddf50dde776ea19b207ef3a7ecaf
add chinese font family
> add chinese font family

- threejs/lessons/zh_cn/threejs-fundamentals.md
Change-Id: I5598f8cb2e4db305dc3448d748373d32fb5f9465
optimize the translation of article threejs-fundamentals
> threejs-fundamentals translation optimize

- threejs/lessons/zh_cn/threejs-fundamentals.md
Reverts gfxfundamentals/threejsfundamentals#157
I'm not sure it makes sense to translate the links. They are referencing important names.
> Revert "threejs-fundamentals translation optimize"

- threejs/lessons/zh_cn/threejs-responsive.md
Change-Id: Id0c68fc92137cdccfae87f30b79741a9dfc9ebfb
> improve threejs-responsive translation

- threejs/lessons/zh_cn/threejs-scenegraph.md
I translate the threejs-scenegraph article to zh_cn
> translate scenegraph to zh_cn

- threejs/lessons/zh_cn/threejs-scenegraph.md
fix my mistake, i'm sorry for my carelessness.
> fix:typo in three-scenegraph on zh_cn

- threejs/lessons/zh_cn/threejs-materials.md
translate threejs-materials to zh-cn
> add: translate threejs-materials to zh_cn

- threejs/lessons/ja/threejs-optimize-lots-of-objects.md
- threejs/lessons/kr/threejs-optimize-lots-of-objects.md
- threejs/lessons/ru/threejs-optimize-lots-of-objects.md
- threejs/lessons/threejs-optimize-lots-of-objects.md
I thingk, in the processing function of fetch, we should use 'response' instead of 'request'.
> Docs: Change 'req' to 'res' for fetch handler

- threejs/lessons/ja/threejs-custom-buffergeometry.md
> Update Japanese translation for custom buffer geometry

- threejs/lessons/zh_cn/threejs-post-processing.md
> feat:post-processing -> cn

- threejs/lessons/zh_cn/threejs-debugging-glsl.md
> Cn debugging glsl

- threejs/lessons/tr/index.md
- threejs/lessons/tr/langinfo.hanson
- threejs/lessons/tr/threejs-fundamentals.md
- threejs/lessons/tr/toc.html
I'm trying to add Turkish language in Three Js Fundamentals. For now, I just add the main pages and starting to translate first page.
> Adding Turkish Language

- package.json
- threejs/lessons/zh_cn/threejs-fog.md
I translate the chapter Fog to Chinese.
> Add Chinese Version of the Chapter Fog

- threejs/lessons/zh_cn/threejs-custom-buffergeometry.md
- threejs/lessons/zh_cn/threejs-rendertargets.md
I translate two lessons to Chinese.
As to the chapter of custom-buffergeometry, I haven't notice the comment below until I finished the translation.
needed in English only to prevent warning from outdated translations
I do the translation because I find that it helps me learn better. If translating this chapter is not allowed, please reject my second commit. Thank you.
> Add Chinese version of rendertargets and custom-buffergeometry

- threejs/lessons/threejs-optimize-lots-of-objects-animated.md
- threejs/threejs-lots-of-objects-morphtargets-w-colors.html
- threejs/threejs-lots-of-objects-morphtargets.html
This PR fixes a repeating bug in [Three.js Optimize Lots of Objects Animated](https://threejsfundamentals.org/threejs/lessons/threejs-optimize-lots-of-objects-animated.html)
It's not actually a bug in visual, but it's repeating unnecessary code block.
So, the PR will fix the code templates and source code of the examples.
N/A
Closes #N/A
> Fix a repeating bug in lession threejs-optimize-lots-of-objects-animated

- threejs/lessons/zh_cn/threejs-picking.md
> add  translation for  threejs-picking in zh_cn
